---
title: "ADA FL21 Midterm"
author: "Noah Wolthausen"
date: "10/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}

library(dplyr)
library(tidyverse) #Load necessary packages

#Upload dataset from github
BRFSS_data <-
  read_csv("https://raw.githubusercontent.com/kijohnson/ADA-Fall-2021/master/BRFSS2017_10percent_v.csv")

#Variable for sex recoded as a factor
BRFSS_data$sex_factor<-factor(BRFSS_data$SEX,
                        levels = c(1,2),
                        labels = c("Male","Female"))

#Median heights for each sex category
BRFSS_data %>%
  group_by(sex_factor) %>%
  summarise(median(ht_meters, na.rm = TRUE))

#Boxplot of median height differences for each sex category
ggplot(data = BRFSS_data, aes(x = sex_factor, y = ht_meters)) +
  geom_boxplot(aes(color = sex_factor)) +
  labs(x = "Sex", y = "Height (meters)",  title = "Differences in height by sex")
  stat_summary(fun = median, geom = "point", shape=23, size=4, na.rm = TRUE)
 #Mean heights by sex category
BRFSS_data %>%
  group_by(sex_factor) %>%
  summarise(mean(ht_meters, na.rm = TRUE))

```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
